version: "3"

services:
  bot:
    build:
      context: ./bot
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    restart: unless-stopped

  site:
    build:
      context: ./site
    ports:
      - "${SITE_PORT:-8080}:8080"
    environment:
      - HOST=${SITE_HOST:-0.0.0.0}
      - PORT=${SITE_PORT:-8080}
    restart: unless-stopped
